apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-app-rollout
spec:
  replicas: 4
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: ayushthe1/go-app:42
          ports:
            - containerPort: 8081
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {}
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 50
      - pause: {duration: 10}
      - setWeight: 100
  revisionHistoryLimit: 2
